"""
AiMedico - Global Constants
All hardcoded values that should not live in config or environment variables.
"""

# ── Medical Disclaimer ────────────────────────────────────────────────────────

MEDICAL_DISCLAIMER_EN = (
    "⚠️ IMPORTANT DISCLAIMER: This information is generated by an AI assistant "
    "and is for educational purposes only. It is NOT a substitute for professional "
    "medical advice, diagnosis, or treatment. Always consult a qualified healthcare "
    "provider before making any medical decisions. AiMedico is not a medical device."
)

MEDICAL_DISCLAIMER_BN = (
    "⚠️ গুরুত্বপূর্ণ দাবিত্যাগ: এই তথ্য একটি AI সহকারী দ্বারা তৈরি এবং "
    "শুধুমাত্র শিক্ষামূলক উদ্দেশ্যে। এটি পেশাদার চিকিৎসা পরামর্শ, রোগ নির্ণয় "
    "বা চিকিৎসার বিকল্প নয়। যেকোনো চিকিৎসা সিদ্ধান্ত নেওয়ার আগে সর্বদা একজন "
    "যোগ্য স্বাস্থ্যসেবা প্রদানকারীর সাথে পরামর্শ করুন।"
)

# ── Emergency Keywords ────────────────────────────────────────────────────────

EMERGENCY_KEYWORDS_EN = [
    "chest pain", "heart attack", "stroke", "difficulty breathing",
    "severe bleeding", "unconscious", "unresponsive", "emergency",
    "urgent", "icu", "intensive care", "anaphylaxis", "seizure",
    "overdose", "poisoning", "suicide", "self-harm", "collapse",
    "cardiac arrest", "respiratory failure", "severe allergic reaction",
]

EMERGENCY_KEYWORDS_BN = [
    "বুকে ব্যথা", "হার্ট অ্যাটাক", "স্ট্রোক", "শ্বাসকষ্ট",
    "তীব্র রক্তক্ষরণ", "জরুরি", "আইসিইউ", "জরুরি অবস্থা",
    "মারাত্মক", "অচেতন", "খিঁচুনি", "অতিরিক্ত ডোজ",
]

# ── Emergency Levels ──────────────────────────────────────────────────────────

class EmergencyLevel:
    NONE = "none"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


# ── Supported Languages ───────────────────────────────────────────────────────

class SupportedLanguage:
    ENGLISH = "en"
    BANGLA = "bn"

SUPPORTED_LANGUAGES = [SupportedLanguage.ENGLISH, SupportedLanguage.BANGLA]

# ── File Upload ───────────────────────────────────────────────────────────────

class FileType:
    IMAGE = "image"
    PDF = "pdf"
    UNKNOWN = "unknown"

IMAGE_EXTENSIONS = {"jpg", "jpeg", "png", "webp", "tiff", "bmp"}
PDF_EXTENSIONS = {"pdf"}

# ── OCR ───────────────────────────────────────────────────────────────────────

class OCREngine:
    TESSERACT = "tesseract"
    EASYOCR = "easyocr"

# ── AI Result Status ──────────────────────────────────────────────────────────

class AIResultStatus:
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"

# ── User Roles ────────────────────────────────────────────────────────────────

class UserRole:
    USER = "user"
    ADMIN = "admin"
    DOCTOR = "doctor"   # Future

# ── Prescription Status ───────────────────────────────────────────────────────

class PrescriptionStatus:
    UPLOADED = "uploaded"
    OCR_DONE = "ocr_done"
    AI_DONE = "ai_done"
    FAILED = "failed"

# ── Pagination ────────────────────────────────────────────────────────────────

DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# ── Token Types ───────────────────────────────────────────────────────────────

class TokenType:
    ACCESS = "access"
    REFRESH = "refresh"
